/**
 * Standard Error Codes
 * Centralized error codes for consistent error handling
 */
module.exports = {
    // Authentication & Authorization
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    DUPLICATE_USER: 'DUPLICATE_USER',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    WEAK_PASSWORD: 'WEAK_PASSWORD',
    INVALID_OTP: 'INVALID_OTP',
    OTP_EXPIRED: 'OTP_EXPIRED',
    TOKEN_EXPIRED: 'TOKEN_EXPIRED',
    TOKEN_INVALID: 'TOKEN_INVALID',
    UNAUTHORIZED: 'UNAUTHORIZED',
    FORBIDDEN: 'FORBIDDEN',

    // Validation
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    MISSING_FIELDS: 'MISSING_FIELDS',
    INVALID_EMAIL: 'INVALID_EMAIL',
    INVALID_PHONE: 'INVALID_PHONE',

    // Resources
    NOT_FOUND: 'NOT_FOUND',
    ALREADY_EXISTS: 'ALREADY_EXISTS',

    // Upload
    UPLOAD_FAILED: 'UPLOAD_FAILED',
    INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
    FILE_TOO_LARGE: 'FILE_TOO_LARGE',

    // Booking/Cart
    SLOT_UNAVAILABLE: 'SLOT_UNAVAILABLE',
    ITEM_NOT_FOUND: 'ITEM_NOT_FOUND',
    DUPLICATE_BOOKING: 'DUPLICATE_BOOKING',

    // Database
    DATABASE_ERROR: 'DATABASE_ERROR',

    // Server
    SERVER_ERROR: 'SERVER_ERROR',
    NETWORK_ERROR: 'NETWORK_ERROR',
    TIMEOUT: 'TIMEOUT',

    // Email
    EMAIL_SEND_FAILED: 'EMAIL_SEND_FAILED',

    // Payment
    PAYMENT_FAILED: 'PAYMENT_FAILED',
    INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE'
};
